eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    #    prefer-ip-address: false
    #    hostname: localhost
    #    instance-id: 127.0.0.1:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
